version: '3.3'
services:
  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'shopxpress-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_SSL_MODE: 'DISABLED' # Disable SSL
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3406:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - shopxpress-db:/var/lib/mysql
# Names our volume
volumes:
  shopxpress-db: